// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDapaMyscbip3Tm_3W6dTAKkcRTVbmGHYM',
    appId: '1:831782100142:web:26da00f0e205902472613f',
    messagingSenderId: '831782100142',
    projectId: 'petcade',
    authDomain: 'petcade.firebaseapp.com',
    storageBucket: 'petcade.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwrhqQBfiTaR2lxP03VS5MWERZ9gwHXac',
    appId: '1:831782100142:android:a24bb3b848ff719372613f',
    messagingSenderId: '831782100142',
    projectId: 'petcade',
    storageBucket: 'petcade.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNS8eGsh1zR5rIsJYQcQOe2FJuGTEfknk',
    appId: '1:831782100142:ios:b95e0e1d8ffee76372613f',
    messagingSenderId: '831782100142',
    projectId: 'petcade',
    storageBucket: 'petcade.firebasestorage.app',
    iosBundleId: 'com.example.petcade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNS8eGsh1zR5rIsJYQcQOe2FJuGTEfknk',
    appId: '1:831782100142:ios:b95e0e1d8ffee76372613f',
    messagingSenderId: '831782100142',
    projectId: 'petcade',
    storageBucket: 'petcade.firebasestorage.app',
    iosBundleId: 'com.example.petcade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDapaMyscbip3Tm_3W6dTAKkcRTVbmGHYM',
    appId: '1:831782100142:web:e3451f91720ba41972613f',
    messagingSenderId: '831782100142',
    projectId: 'petcade',
    authDomain: 'petcade.firebaseapp.com',
    storageBucket: 'petcade.firebasestorage.app',
  );
}
